default: &default
  adapter: postgresql
  encoding: unicode
  template: template0
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: boonbee_development
  username: moiz
  password:

test:
  <<: *default
  database: boonbee_test
  
production:
  <<: *default
  database: freelance_production
